In [1]:
import torch

In [2]:
tensor1 = torch.Tensor([[1,2,3],
                        [4,5,6]])
tensor1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
tensor2 = torch.Tensor([[7,8,9],
                        [10,11,12]])
tensor2

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [4]:
# When true, will track computations in the forward phase and will track gradients in the backward phase
tensor1.requires_grad

False

In [5]:
# updated inplace
tensor1.requires_grad_()

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [6]:
tensor1.requires_grad

True

In [7]:
# no gradients available yet, need to perform a computation, e.g. a forward/backward pass
print(tensor1.grad)

None


In [8]:
print(tensor1.grad_fn)

None


In [9]:
output_tensor = tensor1 * tensor2

In [10]:
# this value is based on the required_grad property of the input tensors, i.e. tensor1
output_tensor.requires_grad

True

In [11]:
# No gradients as have not perfomed a backward pass
print(output_tensor.grad)

None


C:\Users\priye\AppData\Local\Temp\ipykernel_21740\3921303338.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:485.)
  print(output_tensor.grad)


In [12]:
# Has a grad function because of the multiplication
print(output_tensor.grad_fn)

In [13]:
# The input tensors still have no grad function
print(tensor1.grad_fn)
print(tensor2.grad_fn)

None
None


In [14]:
# grad function references the last operation
output_tensor = (tensor1 * tensor2).mean()
print(output_tensor.grad_fn)

In [15]:
print(tensor1.grad)

None


In [16]:
output_tensor.backward()

In [17]:
print(tensor1.grad)

tensor([[1.1667, 1.3333, 1.5000],
        [1.6667, 1.8333, 2.0000]])


In [20]:
tensor1.grad.shape, tensor1.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [21]:
# There are no gradients on tensor2 as the requires grad property was not set
print(tensor2.grad)

None


In [22]:
# No gradients with output sensor
print(output_tensor.grad)

None


C:\Users\priye\AppData\Local\Temp\ipykernel_21740\1906321212.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:485.)
  print(output_tensor.grad)


In [23]:
# Inherits requires grad from tensor1
new_tensor = tensor1 * 3
print(new_tensor.requires_grad)

True


In [24]:
new_tensor

tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)

In [25]:
# requires_grad not propagated to new_tensor as it was created in the no_grad block
# tensor1 retains it's requires grad property
with torch.no_grad():
    new_tensor = tensor1 * 3
    print('new_tensor = ', new_tensor)
    print('requires_grad for tensor1 = ', tensor1.requires_grad)
    print('requires_grad for tensor2 = ', tensor2.requires_grad)
    print('requires_grad for new_tensor = ', new_tensor.requires_grad)

new_tensor =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
requires_grad for tensor1 =  True
requires_grad for tensor2 =  False
requires_grad for new_tensor =  False


In [26]:
def calculate(t):
    return t * 2

In [27]:
@torch.no_grad()
def calculate_with_no_grad(t):
    return t * 2

In [29]:
result_tensor = calculate(tensor1)
result_tensor

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], grad_fn=<MulBackward0>)

In [30]:
# gradient tracking turned off by the decorator even though tensor1 had grad enabled
result_tensor_no_grad = calculate_with_no_grad(tensor1)
result_tensor_no_grad

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [32]:
# can nest an inner block to enable grad
with torch.no_grad():
    new_tensor_no_grad = tensor1 * 3
    print('new_tensor_no_grad = ', new_tensor_no_grad)
    with torch.enable_grad():
        new_tensor_grad = tensor1 * 3
        print('new_tensor_grad = ', new_tensor_grad)


new_tensor_no_grad =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
new_tensor_grad =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)


In [34]:
tensor_one = torch.tensor([[1.0, 2.0],
                           [3.0, 4.0]], requires_grad=True)
tensor_one

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [39]:
tensor_two = torch.tensor([[5.0, 6.0],
                           [7.0, 8.0]])
tensor_two

tensor([[5., 6.],
        [7., 8.]])

In [37]:
tensor_one.requires_grad

True

In [40]:
tensor_two.requires_grad_()

tensor([[5., 6.],
        [7., 8.]], requires_grad=True)

In [41]:
final_tensor = (tensor_one + tensor_two).mean()
final_tensor

tensor(9., grad_fn=<MeanBackward0>)

In [42]:
final_tensor.requires_grad

True

In [43]:
# only performed forward pass so no gradients on the input tensor
print(tensor_one.grad)

None


In [44]:
final_tensor.backward()

In [45]:
print(tensor_one.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [46]:
print(tensor_two.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [48]:
# will create a new tensor with requires_grad set to false
detached_tensor = tensor_one.detach()
detached_tensor

tensor([[1., 2.],
        [3., 4.]])

In [49]:
# use the detached tensor in a computation
mean_tensor = (tensor_one + detached_tensor).mean()
mean_tensor.backward()

In [50]:
tensor_one.grad

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [51]:
detached_tensor.grad