In [1]:
import torch

In [2]:
torch.__version__

'1.13.0'

In [3]:
torch.get_default_dtype()

torch.float32

In [6]:
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()

torch.float64

In [8]:
torch_arr = torch.Tensor([[1,2,3], [4,5,6]])
torch_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [9]:
torch.is_tensor(torch_arr)

True

In [10]:
torch.numel(torch_arr)

6

In [11]:
torch_arr.shape

torch.Size([2, 3])

In [13]:
# PyTorch allocates the memory for a tensor but does not initialise the values
tensor_uninitialised = torch.tensor(2,2)
tensor_uninitialised

tensor([[1.1034e-312, 9.7612e-313],
        [1.1034e-312, 1.9098e-312]])

In [14]:
tensor_initialised = torch.rand(2,2)
tensor_initialised

tensor([[0.8868, 0.3604],
        [0.8557, 0.3366]])

In [17]:
tensor_int = torch.tensor([5,3]).type(torch.IntTensor)
tensor_int

tensor([5, 3], dtype=torch.int32)

In [18]:
tensor_short = torch.ShortTensor([1.0,2.0,3.0])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

In [19]:
tensor_float = torch.tensor([1.0,2.0,3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

In [21]:
tensor_fill = torch.full([2,6], fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

In [23]:
tensor_of_ones = torch.ones([2,4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [24]:
tensor_of_zeros = torch.zeros_like(tensor_of_ones)
tensor_of_zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [27]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [28]:
# Shows the position of non zero values in a tensor
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [30]:
# create a sparse matrix by specifying the coordinate positions in i and the values in v
i = torch.tensor([[0,1,1],
                  [2,2,0]])
v = torch.tensor([3,4,5], dtype=torch.float32)
spare_tensor = torch.sparse_coo_tensor(i, v, [2, 5])
spare_tensor

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

In [31]:
spare_tensor.shape

torch.Size([2, 5])

In [33]:
spare_tensor.to_dense()

tensor([[0., 0., 3., 0., 0.],
        [5., 0., 4., 0., 0.]], dtype=torch.float32)

In [34]:
initial_tensor = torch.rand(2, 3)
initial_tensor

tensor([[0.0879, 0.0633, 0.9222],
        [0.2792, 0.4203, 0.0859]])

In [35]:
# inplace operation - function has suffix _
initial_tensor.fill_(10)
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [36]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [37]:
initial_tensor.add_(8)
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [38]:
new_tensor.sqrt_()
new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [39]:
# torch shares many operations with numpy
x = torch.linspace(start=0.1, end=10, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [43]:
# split a tensor into 3 chunks, the last parameter is the dimension in which to split the tensor
tensor_chunk = torch.chunk(x, 3, 0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [48]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3., 4., 5.])
tensor_concat = torch.cat((tensor1, tensor2, tensor3), 0)
tensor_concat

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [49]:
random_tensor = torch.tensor([[10, 8, 30], [40, 5, 6], [12, 2, 21]])
random_tensor

tensor([[10,  8, 30],
        [40,  5,  6],
        [12,  2, 21]])

In [50]:
# can index pytorch tensors
random_tensor[0, 1]

tensor(8)

In [51]:
# from row 1 onwards and column 1 onwards
random_tensor[1:, 1:]

tensor([[ 5,  6],
        [ 2, 21]])

In [52]:
random_tensor.size()

torch.Size([3, 3])

In [53]:
# view function still uses the same underlying memory, a new tensor is not created
# need to ensure the new shape is compatible with the old
resized_tensor = random_tensor.view(9)
resized_tensor

tensor([10,  8, 30, 40,  5,  6, 12,  2, 21])

In [54]:
resized_tensor.size()

torch.Size([9])

In [55]:
random_tensor[2,2] = 100
resized_tensor

tensor([ 10,   8,  30,  40,   5,   6,  12,   2, 100])

In [56]:
random_tensor

tensor([[ 10,   8,  30],
        [ 40,   5,   6],
        [ 12,   2, 100]])

In [57]:
random_tensor.shape

torch.Size([3, 3])

In [59]:
# Unsqueeze adds an additional dimension at index 2 (the inner most dimension)
tensor_unsqueeze = torch.unsqueeze(random_tensor, 2)
tensor_unsqueeze

tensor([[[ 10],
         [  8],
         [ 30]],

        [[ 40],
         [  5],
         [  6]],

        [[ 12],
         [  2],
         [100]]])

In [60]:
tensor_unsqueeze.shape

torch.Size([3, 3, 1])

In [61]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [62]:
# swap dimensions 0 and 1 of a tensor
tensor_transpose = torch.transpose(initial_tensor, 0, 1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

In [63]:
random_tensor

tensor([[ 10,   8,  30],
        [ 40,   5,   6],
        [ 12,   2, 100]])

In [65]:
# by default will sort by the last index
sorted_tensor, sorted_indices = torch.sort(random_tensor)
sorted_tensor

tensor([[  8,  10,  30],
        [  5,   6,  40],
        [  2,  12, 100]])

In [66]:
# index position in the new tensor
# e.g for row 0 the element now in index 0 was originally in index 2, 
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [67]:
tensor_float = torch.FloatTensor([-1.1, -2.2, -3.3])
tensor_float

tensor([-1.1000, -2.2000, -3.3000], dtype=torch.float32)

In [68]:
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000], dtype=torch.float32)

In [69]:
rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))

In [70]:
add1 = rand1 + rand2
add1

tensor([[1.9269, 1.7857, 1.3761],
        [0.2691, 3.2174, 0.7072]])

In [71]:
add2 = torch.add(rand1, rand2)
add2

tensor([[1.9269, 1.7857, 1.3761],
        [0.2691, 3.2174, 0.7072]])

In [72]:
tensor = torch.tensor([[-1, -2, -3],
                       [1, 2, 3]])

In [73]:
tensor_div = torch.div(tensor, tensor + 0.3)
tensor_div

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])

In [74]:
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1, 4, 9],
        [1, 4, 9]])

In [75]:
# limit the tensor values to a range
tensor_clamp = torch.clamp(tensor, min=-0.2, max=2)
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

In [76]:
t1 = torch.tensor([1, 2])
t2 = torch.tensor([10, 20])

In [77]:
dot_product = torch.dot(t1, t2)
dot_product

tensor(50)

In [ ]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
vector = torch.tensor([0, 1, 2])