In [1]:
import torch

from torch.autograd import Variable

In [2]:
# In previous versions of PyTorch variables used to wrap tensors and was used with autograd
# Variables are now deprecated and no longer needed
# The grad is now part of the tensor itself
var = Variable(torch.FloatTensor([9]))
var

tensor([9.])

In [3]:
var.requires_grad

False

In [4]:
var.requires_grad_()

tensor([9.], requires_grad=True)

In [5]:
w1 = Variable(torch.FloatTensor([3]), requires_grad=True)
w2 = Variable(torch.FloatTensor([7]), requires_grad=True)

In [6]:
w1

tensor([3.], requires_grad=True)

In [7]:
w2

tensor([7.], requires_grad=True)

In [8]:
result_var = var * w1
result_var

tensor([27.], grad_fn=<MulBackward0>)

In [9]:
result_var.requires_grad

True

In [10]:
result_var.backward()

In [11]:
w1.grad

tensor([9.])

In [12]:
w2.grad

In [13]:
var.grad

tensor([3.])