### Conversions between PyTorch and NumPy

In [1]:
import numpy as np
import torch

In [3]:
tensor = torch.rand(4, 3)
tensor

tensor([[0.5773, 0.9225, 0.9660],
        [0.6888, 0.5569, 0.5698],
        [0.0739, 0.3573, 0.6895],
        [0.3050, 0.8994, 0.6990]])

In [4]:
type(tensor)

torch.Tensor

In [6]:
# torch tensors are numpy arrays with the ability to be executed on GPUs
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.5772584 , 0.9224524 , 0.96600515],
       [0.6888324 , 0.5569336 , 0.56979424],
       [0.07394451, 0.35725564, 0.6894745 ],
       [0.30504584, 0.89943147, 0.6989591 ]], dtype=float32)

In [7]:
type(numpy_from_tensor)

numpy.ndarray

In [8]:
torch.is_tensor(tensor)

True

In [9]:
torch.is_tensor(numpy_from_tensor)

False

In [10]:
# The NumPy array and the PyTorch tensor share the same underlying memory
numpy_from_tensor[0, 0] = 100
numpy_from_tensor

array([[1.0000000e+02, 9.2245239e-01, 9.6600515e-01],
       [6.8883240e-01, 5.5693358e-01, 5.6979424e-01],
       [7.3944509e-02, 3.5725564e-01, 6.8947452e-01],
       [3.0504584e-01, 8.9943147e-01, 6.9895911e-01]], dtype=float32)

In [11]:
tensor

tensor([[1.0000e+02, 9.2245e-01, 9.6601e-01],
        [6.8883e-01, 5.5693e-01, 5.6979e-01],
        [7.3945e-02, 3.5726e-01, 6.8947e-01],
        [3.0505e-01, 8.9943e-01, 6.9896e-01]])

In [12]:
numpy_arr = np.array([[1.0, 2.0, 3.0],
                      [10.0, 20.0, 30.0],
                      [100.0, 200.0, 300.0]])
numpy_arr

array([[  1.,   2.,   3.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [13]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [14]:
type(tensor_from_numpy)

torch.Tensor

In [15]:
torch.is_tensor(tensor_from_numpy)

True

In [16]:
# Also share the same underlying memory
tensor_from_numpy[0] = 1
tensor_from_numpy

tensor([[  1.,   1.,   1.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [17]:
numpy_arr

array([[  1.,   1.,   1.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [18]:
np_array_one = np.array([4, 8])
np_array_one

array([4, 8])

In [20]:
# Performs a copy if the data is not already a tensor
# In this case since we are not changing the data type or the device, the new tensor will use the same memory
# This method ensures the data is copied only when needed so unnecessary copies of the data are not made
# New tensor is part of the same computational graph
tensor_from_array_one = torch.as_tensor(np_array_one)
tensor_from_array_one

tensor([4, 8], dtype=torch.int32)

In [21]:
np_array_one[1] = 5
np_array_one

array([4, 5])

In [22]:
tensor_from_array_one

tensor([4, 5], dtype=torch.int32)

In [23]:
np_array_two = np.array([2, 2])
np_array_two

array([2, 2])

In [24]:
# To ensure a copy of the data, use the tensor function
tensor_from_array_two = torch.tensor(np_array_two)
tensor_from_array_two

tensor([2, 2], dtype=torch.int32)

In [25]:
np_array_two[1] = 4
np_array_two

array([2, 4])

In [27]:
# In this case the original data remains unchanged
tensor_from_array_two

tensor([2, 2], dtype=torch.int32)